name: 'diff'
run-name: 'mukai-test-diff'
on:
  pull_request:
    types: [opened, synchronize]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACC_K }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.ACC_P }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Lambroll-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fujiwara/lambroll@v0
        with:
            version: v0.14.7
      - name: diff
        run: |
          directories=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | xargs -n 1 dirname | sort | uniq)
          for directory in $directories; do
            echo $directory
            if [ -f "$directory/function.json" ]; then
              echo "Changes detected in $directory"
              cd $directory
              lambroll diff >> /tmp/diff.txt
              cd -
            fi
          done
      - name: comment diff
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('/tmp/diff.txt', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `\`\`\`\n${diff}\n\`\`\``
            });

