name: 'diff'
run-name: 'mukai-test-diff'
on:
  pull_request:
    types: [opened, synchronize]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACC_K }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.ACC_P }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  Lambroll-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fujiwara/lambroll@v0
        with:
            version: v0.14.7
      - name: diff
        id: detect-diff
        run: |
          directories=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | xargs -n 1 dirname | sort | uniq)
          DIFF=""
          for directory in $directories; do
            echo "Changes detected in $directory"
            if [ -f "$directory/function.json" ]; then
              cd $directory
              DIFF+=$'\n'$(lambroll diff)
              cd -
            fi
          done
          if [ ${#DIFF} -lt 1 ]; then DIFF="Not detected any contents."; fi
          echo "$DIFF" >> $GITHUB_STEP_SUMMARY
          {
            echo 'LAMBDA_DIFF<<EOF'
            echo "$DIFF"
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: comment diff
        env:
          LAMBDA_DIFF: ${{ steps.detect-diff.outputs.LAMBDA_DIFF }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "
          \`\`\`diff
          $LAMBDA_DIFF
          \`\`\`
          "
